# Generated by Django 4.1 on 2022-08-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_task_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
